name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  units:
    name: Units
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15.11.0'
        cache: npm
    - run: npm ci
    - run: npm test
